require_relative "helper/podfile_options"
require_relative "helper/prebuild_sandbox"
require_relative "helper/passer"
require_relative "helper/names"
require_relative "helper/target_checker"
require_relative "integration/source_installer"
require_relative "integration/installer"
require_relative "integration/correcting_embed_framework_script"
