platform :ios, '10.0'

def is_pod_binary_cache_enabled
  ENV['IS_POD_BINARY_CACHE_ENABLED'] == 'true'
end

if is_pod_binary_cache_enabled
  plugin 'cocoapods-binary-cache'
  # set_custom_xcodebuild_options_for_prebuilt_frameworks :simulator => "DEBUG_INFORMATION_FORMAT=dwarf", :device => "ARCHS=arm64 DEBUG_INFORMATION_FORMAT=dwarf"

  # TODO: BUILD_LIBRARY_FOR_DISTRIBUTION is to build with library evolution, but it doesn't work in Xcode 10.2 now, need find another way
  # set_custom_xcodebuild_options_for_prebuilt_frameworks :simulator => "BUILD_LIBRARY_FOR_DISTRIBUTION=YES", :device => "ARCHS=arm64 BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
  
  config_cocoapods_binary_cache(
    prebuild_config: "Debug",
    dev_pods_enabled: true
  )
  # set_unbuilt_dev_pods(['ConfigSDK']) // To test ABI breaking (crash, call wrong function) when there're code change in ConfigSDK and don't rebuild it's clients (ConfigService)
end

def binary_pod(name, *args)
  if is_pod_binary_cache_enabled
    pod name, args, :binary => true
  else
    pod name, args
  end
end

target 'PodBinCacheExample' do
  use_frameworks!

  # Pods for PodBinCacheExample
  # https://www.raywenderlich.com/259-top-10-libraries-for-ios-developers

  binary_pod 'AFNetworking', '3.2.1'
  binary_pod 'SDWebImage'
  binary_pod 'Alamofire'
  binary_pod 'MBProgressHUD'
  binary_pod 'Masonry'
  binary_pod 'SwiftyJSON'
  binary_pod 'SVProgressHUD'
  binary_pod 'MJRefresh'
  binary_pod 'CocoaLumberjack'
  binary_pod 'Realm'
  binary_pod 'SnapKit'
  binary_pod 'Kingfisher'

  # Example of Vendor pod with external source from git
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :commit => 'a580d07ed002217fd91d8446c3a852486e9beefa', :binary => true

  # Development/Local Pods
  pod 'ConfigService', :path => 'DevPods/ConfigService', :binary => true
  pod 'ConfigSDK', :path => 'DevPods/ConfigSDK', :binary => true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES' # Only work from Xcode 11
    end
  end
end
