platform :ios, "12.0"
use_frameworks!

source "https://cdn.cocoapods.org/"

def binary_pod(name, *args, **kwargs)
  kwargs_cloned = kwargs.clone
  kwargs_cloned[:binary] = true if kwargs_cloned[:binary].nil?
  pod name, *args, **kwargs_cloned
end

plugin "cocoapods-binary-cache"
config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "local" => ENV["PREBUILT_CACHE_LOCAL_DIR"] || "prebuilt_cache/default" # use local cache for integration tests
    }
  },
  excluded_pods: [],
  dev_pods_enabled: true,
  save_cache_validation_to: ".stats/cocoapods_binary_cache.json",
  strict_diagnosis: true, # Fail if any abnormal integration is spotted
  xcodebuild_log_path: ".logs/xcodebuild",
  xcframework: ENV["USE_XCFRAMEWORK"] == "true"
)

target "PrebuiltPodIntegration" do
  # Has `*.bundle` outside the framework
  binary_pod "SwiftDate", "6.1.0"
  binary_pod "BKMoneyKit", "0.0.12"
  binary_pod "IQKeyboardManagerSwift", "6.1.1"
  binary_pod "GoogleSignIn", "4.2.0"

  # Has `*.bundle` inside the framework
  binary_pod "GoogleMaps", "2.7.0"

  binary_pod "UICommonsStatic", :path => "LocalPods/UICommonsStatic"
  binary_pod "UICommonsDynamic", :path => "LocalPods/UICommonsDynamic"

  target "PrebuiltPodIntegrationTests" do
    inherit! :search_paths
  end
end

pre_install do |installer|
  must_be_dynamic_frameworks = []
  installer.pod_targets.each do |pod|
    linkage = must_be_dynamic_frameworks.include?(pod.name) ? :dynamic : :static
    pod.instance_variable_set(:@build_type, Pod::BuildType.new(:linkage => linkage, :packaging => :framework))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["SWIFT_SUPPRESS_WARNINGS"] = "YES"
      config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
    end
  end
end
